services:
  - type: web
    name: indian-stock-scanner-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: RENDER
        value: true
      - key: FLASK_ENV
        value: production
