services:
  - type: web
    name: indian-stock-scanner-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: waitress-serve --host=0.0.0.0 --port=$PORT --connection-limit=100 --cleanup-interval=30 app:app
    envVars:
      - key: RENDER
        value: true
      - key: FLASK_ENV
        value: production
